# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate Pull Requests

# Disabled for new monorepo
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci --no-scripts
        env:
          CYPRESS_INSTALL_BINARY: 0
          DISABLE_OPENCOLLECTIVE: 1
      - name: Run Tests (actually build)
        run: npm run build
